spring:
  servlet:
    multipart:
      max-file-size: 10MB      # 파일 하나당 최대 10MB
      max-request-size: 10MB   # 전체 요청당 최대 10MB
  config:
    import: "optional:env[.properties]"
  server:
    port: 8080
  datasource:
    url: jdbc:mysql://${DEFAULT_URL}:3306/${DEFAULT_SCHEMA}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
openai:
  model: gpt-3.5-turbo
  secret-key: ${AI_SECRET_KEY}
api:
  pill:
    service-key: ${SERVICE_KEY}
google:
  application:
    credentials: "google-credential.json"

